### ISSUE TITLE
Request to add Turkish PARS III Mk19 RWS to calculations

### ISSUE THREAD

**Issue by Ferrariic** [sh4rkman/SquadCalc#148] opened 2024-06-05 20:03 UTC
**Situation**: Turkish PARS III MK19 RWS and Marine AAVP Mk19 can accurately hit infantry targets at ranges of up to 5.8km in testing. Realistically, the PARS III has an elevation dial which can be used to justify hitting targets at these extreme ranges. The AAVP MK19 can also hit these ranges, but it cannot be dialed in without a spotter, and therefore should not be added to the mortar calculator. The AAVP MK19 also has a maximum flat elevation of 30°, giving it a range of 5,092m on flat terrain, without 15° vehicle elevation offset to get to 45°.

Turkish MK19 RWS Viewport
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/b8d69db1-27bc-4659-81c3-8de871630e97)

**Problem:** Turkish PARS III MK19 RWS not in calculations dropdown, and would be a very effective indirect fire method.

**Solution:** Add turkish PARS III MK19 RWS to calculations, using muzzle velocity of 240m/s. Vehicle has maximum theoretical elevation of 45°, and a practical elevation of 41°. Range is ~5.8km. Vehicle elevation offset can be indicated as 1.5-3meters, depending upon the vehicle used. 

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/e7744009-5e5b-4ac7-a906-1cd4daaba49c)

Ballistics calculator used, which is accurate in my testing. https://www.omnicalculator.com/physics/range-projectile-motion

**Additional Clarification:** The wiki may be incorrect at listing the muzzle velocity of the mk19 at 230m/s, the calculations work best with 240m/s. Further testing is necessary, though I believe this works best.

**Comment by sh4rkman** [comment] 2024-06-06 18:18
Hi ! Thank you for you interest. 😄

I have already tried something like that in the past with the Turkish Tank that also have elevation in his HUD, but stopped because it was a pain in the ass to test the accuray alone : projectile path was so shallow and fast that i didn't have time to jump in UAV to see where the shots landed.

That being said, i didn't think about MK19 ! It's interesting and can definitly act like a indirect fire support weapon. Specially if as you suggest it has a inredible maxrange of 5km (!!)

I need to check two requirements before accepting your PR : 

1. Find the exact velocity and MOA from SDK (the values you have right now are empirical right?)
2. Test it a bit in a local server at long range with UAV to confirm it's precision and that i'm not pushing a teamkiller feature

The second point is crucial because i have already seen the elevation indicator when inside MK19 is rounded to degrees and i don't want people to think squadcalc isn't precise 👀

**Comment by sh4rkman** [comment] 2024-06-06 18:45
Alright so i found the values from the SDK, it's indeed 230 like the wiki said, but since you mention 240 looks better that will need serious testing from my part.

I saw that you first pushed a MOA of 50 like the SDK and reduced it to 30, was it because ingame testing looked more precise that what squadcalc displayed ?

![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/8c7aaf8d-7c35-45c2-a208-0f0ed031f465)
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/17c12d7b-257b-49a2-be4d-781b4c96a5fd)

**Comment by Ferrariic** [comment] 2024-06-06 19:01
Yeah my values were based upon what I saw in-game vs the wiki, however, if you find that in your testing 230 m/s & 50 moa works, that could be better used. My testing method may not be as precise as yours, jensen's range and then a seperate map like gorodok/talil in out-of-game testing for calculations w/ freecam. Didn't think to use the UAV, will do that for the future. Let me verify with UAV and see what results I get here.

**Comment by sh4rkman** [comment] 2024-06-06 19:18
Yeah i mostly freecam, but with some weapons that have too little time of flight (grad/UB) or when shooting at long distance the UAV/drone is needed.

Ideally, you stand static upper your target, record 10-25 shots and then compile shots on a single image like this to check if shots are centered on target and if spread (moa) is fine :  

![289369607-f2d3d18e-e00e-4f19-a450-1995b1ece8c2.png](https://github.com/sh4rkman/SquadCalc/assets/9033912/cc42fba8-1aa9-43dc-9c6e-75ca8a58ed3f)

**Comment by Ferrariic** [comment] 2024-06-06 19:32
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/46202e01-8e06-41e6-83b9-ce11ac3abbbb)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/bfded371-454d-4bce-b834-d9ae0cfc445e)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/b0395cfe-109d-47dc-b38a-73834e4b5a66)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/1aabf566-6c4f-485e-a02a-a027189190f1)

I performed this short test using the values of 230m/s and 50 moa, overshot batha slightly @ 18° / 230m/s / 50 moa. Here is the clip. will do further testing.

https://medal.tv/games/squad/clips/i12VDq6lK1vYqeIdU/d13377kA873s?invite=cr-MSxQeHgsNzMyMzU0ODQs

**Comment by Ferrariic** [comment] 2024-06-06 20:24
**240 m/s 50 moa spread test**, imho these results are far more accurate than 230m/s @ 50 moa. 

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/bd25556b-2844-4daf-9ae0-239261c87e78)
https://medal.tv/games/squad/clips/i13DSzBao6UNUmRJO/d1337pfTAk6g?invite=cr-MSxlb24sNzMyMzU0ODQs

It seems to be better at **240 m/s**. If you could review these results and let me know what you think.

Here is a comparison between the two landing zones for 17° equivalent (240m/s and 230m/s on the calculator) from E14-4-4-9-7 to Batha center L04-7-5-2-3 using Turkish PARS III Mk19 50 shots.

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/b4141d08-5050-43bd-a1f1-9c3c7cee1795)

**Comment by Ferrariic** [comment] 2024-06-06 22:29
I did another test, 4.2km @ **238m/s 50 moa**, which was closer than 236m/s & 237m/s, on the money at 4.2km.

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/768d9d90-fcd1-4322-baf7-b532d90fe43f)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/ddb116b6-8115-4a4a-9c69-4339d6e04393)
Clip: https://medal.tv/games/squad/clips/i1605HbympkMVyWSP/d1337tB5hY1d?invite=cr-MSxHNHYsNzMyMzU0ODQs

Sorry for the multiple comments btw, lots of testing to see exactly what value works best. we're looking at around 238 m/s now. I don't think 230m/s works.

Summary of testing:
240 m/s calculation undershoots minorly, 230 m/s overshoots majorly. Dialed into 236 which appears good at moderate distances of ~2km. At extreme ranges of 4.1+ km **238m/s is undeniably accurate.** 

Updating the PR. I believe 50 moa is appropriate.

**Comment by Ferrariic** [comment] 2024-06-06 23:00
If you could verify the moa to your specifications, the velocity is now dialed in, that's the last part which needs to be done. Though  50 seems fine, I can't tell the difference between 35 & 50 at that range.

**Comment by sh4rkman** [comment] 2024-06-07 08:00
Thanks a lot for your testing, also played a lot with it yesterday and i'm perplexed.

When reproducing similar test on Tallil (3200m shots) i also found that both 230 & 240 velocity weren't right, and the best was probably in between. 235 looked indeed more precise. Tested another map for the sake of it (elevation should interfere here, the existing system is solid) and at similar distance (3000m) it also looked OK.

But when keeping this 235 velocity and shooting at "short" range (1500m) now shots were again overlapping **by a lot.**

Before even arguing if vel & moa that we find in the SDK are right we have a major problem : in the MK19 HUD degrees are rounded. It makes every tests very approximate because if i feel like i'm kinda halfway between 17° and 18°, i have no idea if i'm aiming at 17.3 or 17.6 or even worst. When using keyboard to adjust elevation i have the feeling that it at 0.5 step each time i press Z but how do i know if i'm jumping from 16, 16.5, 17, 17.5 and not 16.3, 16.8, 17.2, ... 

At this velocities, a 0.3 difference means a 80 meters distance :

![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/7de5ec92-7158-4a73-9b61-2290cf1f1381)

For now and unless owi add a decimal i'd consider the HUD as impracticable and the weapon imprecise as an indirect fire weapon. It feel like in every test i'm doing i'm adjusting the velocity to correct my false elevation inputs, and when switching from target to target what i though was precise isn't anymore

**Comment by Ferrariic** [comment] 2024-06-07 08:13
That's a very reasonable point about the HUD having rounded decimals and the need to retain full accuracy w/ squad calc - I can imagine that some squad players would end up tking with rounded HUD values as it currently stands. 

We may have to patiently await a MK19 platform with decimal points in the HUD for this to be truly accurate in-game, or rely on spotters to adjust fire.

I think you may be able to use flat decimal points to hit very distant targets, but you definitely are not as accurate as a mortar, hellcannon, grad, or UB, and may need to rely on a spotter for minor adjustments.

**Comment by sh4rkman** [comment] 2024-06-07 13:11
Well, use your fork for now and test it in some real live game : let me know if you can get +10kills without leaving main

**Comment by Ferrariic** [comment] 2024-06-07 13:26
Will do, currently traveling abroad for 7 days. I'll be back and test it then. 

The two games that inspired this was when I got kills at 1500-1700 meters from airport as the launch zone using the AAVP at precalculated locations on Narva. Here are those games. I will reproduce this on a larger map using the turkish mk19 from main and post results when I'm back. 

![image-5.png](https://github.com/sh4rkman/SquadCalc/assets/5789682/d208ae52-e142-4e55-8a03-65e128bbe80e)

![image-4.png](https://github.com/sh4rkman/SquadCalc/assets/5789682/2ed5348f-0c03-4ccf-9f2d-2f728eab3cf1)

**Comment by Ferrariic** [comment] 2024-06-10 19:42
Still on vacation, but check this out 👀 

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/3d07eebf-7cca-4b5b-a0fa-472537b09d83)

**Comment by sh4rkman** [comment] 2024-06-10 19:48
Haha you are fast, i'm more exited about the 120mm M1064A3 mortar carrier atm but let's hope this mk19 variant will have precise elevation

**Comment by Ferrariic** [comment] 2024-06-10 19:55
Hope so too! The 120mm M1064A3 will be insane, hope it has precise dials.

**Comment by sh4rkman** [comment] 2024-06-11 07:13
C16 TAPV reticle : 
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/b13fa3ba-d110-47ad-943e-043da8d64ab9)

Emplaced/OpenTop mk19 doesn't have an optic but looks like it can be ranged up to 1500m : 
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/a030c644-80bc-49dc-b58c-56d575229ef0)

**Comment by Ferrariic** [comment] 2024-06-11 09:36
Interesting, 

1. Can you elevate/depress the turret, and if so 
2. Do you know the max elevation or depression? I'm assuming you cannot reset it back to 0°, as if it were an emplaced mg. 
3. Is there an idea of how many degrees are added/subtracted from the turret per 100m increment
4. Is it a dynamic amount per 100m instead of flat?

**Comment by Ferrariic** [comment] 2024-06-14 17:04
Interesting, 

1. Can you elevate/depress the turret, and if so 
2. Do you know the max elevation or depression? I'm assuming you cannot reset it back to 0°, as if it were an emplaced mg. 
3. Is there an idea of how many degrees are added/subtracted from the turret per 100m increment
4. Is it a dynamic amount per 100m instead of flat?

**Comment by SuisQi** [comment] 2024-06-16 01:19
> https://www.reddit.com/r/joinsquad/comments/1dfo3jm/comment/l8l5xdg/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button
> 
> Sent a question of changing the pars dial to a dev on reddit, it appears that it likely won't change as they'd rather not promote the use of vics for indirect fire support, and looking at the mk19 options in-game it wouldn't be too suitable to add to calc as a full model, at best it would be an experimental option with a warning if you do decide.

you can make an accurate ruler sticker and place it on the original scale to be more precise. Also, I would like to ask if your MK19 calculator is accurate, and what are the parameters?

**Comment by Ferrariic** [comment] 2024-06-16 02:56
> > https://www.reddit.com/r/joinsquad/comments/1dfo3jm/comment/l8l5xdg/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button
> > 
> > Sent a question of changing the pars dial to a dev on reddit, it appears that it likely won't change as they'd rather not promote the use of vics for indirect fire support, and looking at the mk19 options in-game it wouldn't be too suitable to add to calc as a full model, at best it would be an experimental option with a warning if you do decide.
> 
> you can make an accurate ruler sticker and place it on the original scale to be more precise. Also, I would like to ask if your MK19 calculator is accurate, and what are the parameters?

Please checkout the active PR attached to this issue for the most precise parameters and testing.

**Comment by Ferrariic** [comment] 2024-06-16 20:49
One of the first games, back, most incaps in the game at 24 / 0 / 13 (Incap, deaths, kills)

Using the AAVP results below:
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/43c68a70-451e-4896-a6e7-2bced2055699)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/039ca744-e191-4764-acb9-061d897b722d)

Made a guide for the new mk19 with accuracy.
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/21fc1026-2891-4385-9670-586e5720cfce)

Requires that you use 19px on a 1920 x 1080p monitor per degree using 238 m/s.

This is the best result we can hope for, and I'm very pleased with it.

**Comment by Ferrariic** [comment] 2024-06-24 02:49
Final update I can really give here, had a lot of really great games w/ this PR and it's as fine tuned as I can make it. The most relevant one is here w/ the Pars III mk19 on Al-Basrah. Most games I've played with other mk19 variants have had similar results.

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/12e545cb-d460-4bdc-b632-a37ff100eb06)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/f20e1e77-4708-4cd3-ac64-47d07b3d0981)

**Comment by sh4rkman** [comment] 2024-06-24 18:07
Alright let's introduce it!

I'll keep a big MOA despite the fact that imo it should be less, but at least it will warn users that it can be way imprecise because of input imprecision

**Comment by Ferrariic** [comment] 2024-06-24 19:30
Wonderful, thanks!

**Comment by sh4rkman** [comment] 2024-06-24 19:33
Give me this week to merge/final test it again (mostly the spread/moa)

I need to deal with m121 nerfs first

**Comment by Ferrariic** [comment] 2024-06-24 19:38
> Give me this week to merge/final test it again (mostly the spread/moa)
> 
> I need to deal with m121 nerfs first

Sounds good, tyvm!

**Comment by Ferrariic** [comment] 2024-06-28 00:00
In reference to the new gravity changes I've run some tests using values in squad calc, with modified gravity and velocity with the mk19 40mm.

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/64308755-1792-43a3-9b01-63aa1817ef9c)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/92b03211-55cb-469d-9563-1977abd392d8)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/bd3dd86b-1e4a-4bb6-8649-8b059cb94071)

I've performed 3 tests at 10°, 15° and 20° PARS III Mk19 elevation on 0° pitch 0° roll terrain on Talil.

Setup
1. Bring Pars III Mk19 to J-13-6-3-8-6 and setup rep station, using UAV in admin cam to gauge target hits. 
2. When elevating the PARS MK19 to the degree of elevation required, use individual pixel counting and mouse movements to bring the mouse from a lower degree to the required degree (ex. 9° -> 10°) and stop when the digital dial reads the required distance.
3. Fire mk19 and mark center cluster.
4. Use SquadCalc with above mix of values to see where the calculator indicates the hit location.

10° Test - 2000 meters, displacement from true center in meters
1° of variance is equal to 194 meters at this range
| Velocity/Gravity | 9.78 m/s2 | | 9.8 m/s2
| --- | --- | --- |
| 238 m/s| **< +/- 5** | **< +/- 5** |
| 240 m/s | +45 | +30 |

15° Test - 2870 meters, displacement from true center in meters
1° of variance is equal to 180 meters at this range
| Velocity/Gravity | 9.78 m/s2 | | 9.8 m/s2
| --- | --- | --- |
| 238 m/s| **< +/- 10** | **< +/- 10** |
| 240 m/s | +85 | +60 |

20° Test - 3600 meters, displacement from true center in meters
1° of variance is equal to 155 meters at this range
| Velocity/Gravity | 9.78 m/s2 | | 9.8 m/s2
| --- | --- | --- |
| 238 m/s| +100 | **+45** |
| 240 m/s | +155 | +138 |

Values are approximate based upon center hit location in each salvo group and calculated with squad calc. 

238 m/s and 9.8 m/s2 seems to work best, but there is definitely some issues with varying range which are better appreciated at longer distance.

**Comment by Ferrariic** [comment] 2024-06-28 04:43
Discovered an issue, referenced above, which pertains to very long range shots >4km on maps which are not completely flat. The skybox seems to prevent the grenades from impacting/hitting the target, this is my assumption as the wiki does not state that the mk19 grenades have a detonation or cleanup time.

**Comment by sh4rkman** [comment] 2024-06-30 18:10
Looking back into SDK to understand why changing gravity to 9.78 doesn't fix everything, i now did find 135m/s attached to MK19. It looks like the 130 velocity i initially found was the AAVP version of the weapon. Lowering the gravity to 9.78 with that new 135 velocity _should_ be the mathematically right solution.

Now, testing with the [Chinese testing workshop mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2848273764) i feel like it's actually hitting right when one tapping left click in semi-auto : it's like your need to adjust velocity is to fight the recoil of the gun.

Problems are starting to add on top of each others.. time of flight limitation, recoil that need to be manually corrected the hacky way, input imprecision, i'm now considering this implemention not viable since i don't want users to extrapolate the imprecision of MK19 to the whole calculator.

OWI don't want the MK19 to be used as indirect weapon and they are kinda right : it would be op as fuck if we could spam 40mm grenade as precisely at a 5km range.

**Comment by Ferrariic** [comment] 2024-06-30 20:25
> Looking back into SDK to understand why changing gravity to 9.78 doesn't fix everything, i now did find 135m/s attached to MK19. It looks like the 130 velocity i initially found was the AAVP version of the weapon. Lowering the gravity to 9.78 with that new 135 velocity _should_ be the mathematically right solution.
> 
> Now, testing with the [Chinese testing workshop mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2848273764) i feel like it's actually hitting right when one tapping left click in semi-auto : it's like your need to adjust velocity is to fight the recoil of the gun.
> 
> Problems are starting to add on top of each others.. time of flight limitation, recoil that need to be manually corrected the hacky way, input imprecision, i'm now considering this implemention not viable since i don't want users to extrapolate the imprecision of MK19 to the whole calculator.
> 
> OWI don't want the MK19 to be used as indirect weapon and they are kinda right : it would be op as fuck if we could spam 40mm grenade as precisely at a 5km range.

Tbh that's second point is very true, It is highly op lol... I am consistently getting the most kills in every game without seeing a single person and it's extremely low effort when you get it set up.
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/16d05674-e9e8-4fe5-8aa5-4c09a7a02892).

But yes to your main point, I completely understand if you don't want to implement this in the calculator because there are a multitude of factors which make it less than viable to the average squad player. If you'd like to shelve this idea until something better (accuracy/etc) comes along that's fine by me. If you don't mind, I'll be using my fork of the calculator for my attacks because it's effective for me.

**Comment by Ferrariic** [comment] 2024-06-30 22:01
235 m/s seems more accurate, I agree.

**Comment by Ferrariic** [comment] 2024-07-01 03:52
> recoil that need to be manually corrected the hacky way

Did you mean the open top 40mms or the other ones? Emplaced ones have no kick it seems, neither do any rws variants which is very nice.

**Comment by Ferrariic** [comment] 2024-07-01 05:30
I think I have a fair solution to this problem and other problems w/ regards to future makeshift weapons: adding a custom weapon option which allows you to input details of the weapon into the calculator. Therefore the onus is not on SquadCalc to be "correct", and users could input any weapon of their choosing that they find in testing.

**Comment by SuisQi** [comment] 2024-07-03 13:00
Can you send a video to see how you use the MK19

**Comment by Ferrariic** [comment] 2024-07-05 03:34
> Can you send a video to see how you use the MK19

I'm sorry I'm doing 100 hr weeks rn in surgery, I won't be on squad for a while, maybe a few months. 

https://github.com/sh4rkman/SquadCalc/issues/148#issuecomment-2171873548

1. Get level ground with vehicle
2. Find horizon
3. Use visual ruler to get degrees
4. Elevate gun to degrees and fire

**Comment by utkuvrs** [comment] 2024-09-03 13:37
There is nothing wrong here, PARS III OP cuz Turkish power.

**Comment by sh4rkman** [comment] 2024-10-06 16:46
done with https://github.com/sh4rkman/SquadCalc/pull/204

**Closed by sh4rkman** 2024-10-06 16:46 UTC
Labels: New feature
