### ISSUE TITLE
The results from the 120mm mortar calculator are inaccurate.

### ISSUE THREAD

**Issue by SuisQi** [sh4rkman/SquadCalc#156] opened 2024-06-13 13:23 UTC
The calculation results have a significant deviation from reality. Although the game doesn't display numbers to two decimal places, players can still make adjustments close to that precision through subtle controls. Despite this, the results from the calculator are still inaccurate. I'm not sure if it's due to my micro-operations not being precise enough, but after numerous tests, I haven't achieved accurate results even once. It seems like there might be an issue with the formula. For the 120mm mortar, there seems to be a drag coefficient parameter, set at 0.01.
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/fd9dc269-7697-492a-820d-057735dacf93)
But I modified the formula, and this coefficient has a negligible effect on the results.

**Comment by sh4rkman** [comment] 2024-06-13 14:06
Re-tested again and it seems on point : the values squadcalc display for elevation is exactly the same as the ingame calculator (900m on flat ground = 82.9, etc). 

Can you provide a recreation of said inacurracy, weapon/target position, screenshot of where the shots fall, map used etc ?

Keep in mind it has a bigger spread than 80mm mortars : 
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/4eb85cf3-9f5d-4f11-a328-4576b0877193)

**Comment by SuisQi** [comment] 2024-06-14 01:10
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/0a714bd4-e5d8-4cd7-b3fe-f6d850680829)
Here is the position of the 120mm mortar.
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/6eb90ee4-d250-40ea-9bb7-8d11aef2129c)
This is the position of the point, and it is precisely 83.00 to two decimal places

But when I went into the game and moved from 82.9 to 83.0 and fired three mortars, each time from 82.9 to 83.0, the impact points were scattered and not on this point.
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/409ad981-2cab-4c00-b074-dc82b8a4338e)
As shown in the picture, the three impact points are on the three red helmets I marked

**Comment by sh4rkman** [comment] 2024-06-14 08:56
The higher the angle is, the higher the ratio degree/distance is. Aka adding or removing 0.05degree of imprecision at high angle can mean 10m of horizontal distance when it's will be 1m at low angle (the closer you get to 45deg). With 120mm using degree with only one decimal and not mils if can lead up to 8-10 meters imprecision between 82.86 and 82.94.

The ingame range calculator shows this imprecision : for 82.9 and by very slightly moving my mouse i can achieve both 900 & 910m : 

![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/33c0a5ed-e391-48b6-85b3-002dae148451)
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/95c56302-5938-4797-93cb-44acd1b4fb19)

So my first thought would be that that the lack of decimal added to the natural dispertion can lead to this shots overlapping. That being said it looks like shots are overlapping target more than they are falling too short. As i'm not taking the vehicule high into account, it could be the reason aswell..

There is definitly no air friction into the game, already looked for the possibility in the past, they are using the classic projetile motion formula

![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/d575bce6-c762-46e2-9d17-5b149e190ba2)

Which is :

**Comment by SuisQi** [comment] 2024-06-14 09:04
No, I specifically wrote a program that can precisely adjust to two decimal places in mils. When firing five consecutive shots, sometimes all five almost hit the same spot, but the results differ from the calculator by more than 10 meters.

**Comment by SuisQi** [comment] 2024-06-14 09:09
Manually, you can also adjust from 77.9 to 78.0, which will be very close to 78.00. I have tested this many times in the training ground, and I suggest you try it as well

**Comment by SuisQi** [comment] 2024-06-14 09:10
Changing gravity to 981 has a very small effect on the results, so it shouldn't be the issue. Is the speed of 190 accurate?

**Comment by sh4rkman** [comment] 2024-06-14 09:13
> No, I specifically wrote a program that can precisely adjust to two decimal places in mils.

is it a program that adjust the ingame precision or a out of game calculator that gives you more decimals ?

**Comment by SuisQi** [comment] 2024-06-14 09:19
> > No, I specifically wrote a program that can precisely adjust to two decimal places in mils.
> 
> is it a program that adjust the ingame precision or a out of game calculator that gives you more decimals ?

No, moving the mouse 50 units equals 0.1 degrees. The program first adjusts to the next position, for example, if the target is 78.74, it will first adjust to 78.6, then move up 5 units at a time until it reaches 78.7, which is already very close to 78.70. Then, it moves up 4 more units (4*5) to get very close to 78.74.

![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/8920e04f-7449-40c5-ae52-94ea319b6a3d)

**Comment by SuisQi** [comment] 2024-06-14 10:33
https://github.com/sh4rkman/SquadCalc/assets/160198334/c686437e-ea08-41c8-a603-f4a71d946633

Watch this video.，The mils are almost at a single point; the azimuth might have some deviation, but they are all 3.8.

![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/04e114dc-4e35-46d0-b871-7407eab84cb4)
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/e999ea46-a6d6-4548-96eb-d3be2343952f)
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/8abfab95-3f87-4350-b741-de62fc01a836)

**Comment by sh4rkman** [comment] 2024-06-14 10:44
Same scenario, adjusting to 78.0 coming from 78.1 : 
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/1b8e6ebe-3f89-416a-8d04-c79ff7f12e7f)

I'm afraid i can't do better unless OWI add another decimal so i can rule out the possibility of input rounding error.

**Comment by sh4rkman** [comment] 2024-06-14 10:48
That being i agree that shots are overlapping most of the time, maybe the 190m/s isn't right and could be adjusted to 195m/s but unless someone find something better in the SDK i have no real reason to change the value

**Comment by SuisQi** [comment] 2024-06-14 13:23
![D1CE15E2F40923FB63BE15D637F6EEDB](https://github.com/sh4rkman/SquadCalc/assets/160198334/9f9f1500-b158-4af7-aea7-51bf0fd5d54b)
Your gs is the value from the in-game calculator, which is inaccurate. The value of g should be closer to 10
![1AFDBC43B196041A431C6CC03634A1F3](https://github.com/sh4rkman/SquadCalc/assets/160198334/ee6a159a-92e0-4eef-b929-e51bb3490604)

**Comment by sh4rkman** [comment] 2024-06-14 13:52
Yes i know! It's the only gravity value i can find in the SDK. 
I'f i use g = 10, the shots are 150/200m too long

**Comment by SuisQi** [comment] 2024-06-15 02:58
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/f011ad20-22e1-46a6-8c7d-51f07ac7d53b)
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/4e6552d4-957f-48de-92ca-5e8953359274)
Experiments show that the calculated results are closer than the actual results.

**Comment by sh4rkman** [comment] 2024-06-15 08:20
What are the differences here in term of velocity/gravity ?

**Comment by SuisQi** [comment] 2024-06-15 08:27
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/06f8293e-ca70-4525-9d2a-0c5dc699a7f8)
The target was supposed to be at my red arrow, but the actual walk was longer than expected

**Comment by SuisQi** [comment] 2024-06-15 08:38
> What are the differences here in term of velocity/gravity ?

That's what you use for your parameters

**Comment by sh4rkman** [comment] 2024-06-16 18:13
I might deploy a fix soon but since i still have no idea where the problem is coming from, it will be a very ugly hack/fix.

I will either : 
* Round the elevation to the next decimal (8.12 -> 8.20)
* add a raw +0.1 on every results
* Slightly increase velocity (like from 190 to 192 or something)

I hate to do this because every other weapon from squadcalc use the classic formula and velocity from the SDK and work like a charm. If anybody find out why shots are overlapping i'm all ears

**Comment by SuisQi** [comment] 2024-06-17 03:54
> I might deploy a fix soon but since i still have no idea where the problem is coming from, it will be a very ugly hack/fix.
> 
> I will either :
> 
> * Round the elevation to the next decimal (8.12 -> 8.20)
> * add a raw +0.1 on every results
> * Slightly increase velocity (like from 190 to 192 or something)
> 
> I hate to do this because every other weapon from squadcalc use the classic formula and velocity from the SDK and work like a charm. If anybody find out why shots are overlapping i'm all ears

No, actually, regular mortars are also inaccurate, it's just that their error margin is not as large.

**Comment by sh4rkman** [comment] 2024-06-25 23:18
After some more reasearch and a lot of testing, you are indeed right : every weapons are overlapping target by 1-3 meters on average, sometime more with high velocities weapons. Classic mortar are hitting perfectly, because historically squadmc, squadxyz and squadcalc never used the 110 m/s velocity found in the SDK but a corrected, approximated value of 109.89m/s. It  has always been like this, i even forgot about that and though i was using SDK value. In the same way of we approximated velocity for classic mortars we should have also approximated the others velocities, but no one did.

Since shots are too long, it's not air-resistance or whatsoever. Only thing left in the equation is gravity. Every calculators have been using 9.8 blindly, it looks like it's UE4 default value but maybe OWI use something along 9.75 that actually fix every weapon all at once.

I'll still dig up a bit / ask OWI what gravity they are using since i can't find it anywhere in the SDK

**Comment by sh4rkman** [comment] 2024-06-26 22:29
After another shitload round of testing, i found that a gravity of 9.78 seems to fix everything : classic mortar are slightly different with g= 9.78 and vel=110 (in comparison of g=9.8 and vel=109.89) but that's barely noticeable. It might be even closer to reality now.

Every other weapon tested seems to be working very precisely, fixing the 1-3meters overlap on M121 and  HellCanon.
I didn't test GRAD/UB for now but calcs are barely changing (-0.1 at long distance at worst, it's was surely wrong too)

That 9.78 that i found while testing is not some random numbers after a quick research : this is [the consensus of gravity at the equator](https://en.wikipedia.org/wiki/Gravity#Earth's_gravity), while 9.8 is the average gravity on earth. Looks like OWI is using this value in squad instead.

I'll be pushing a fix soon with updated values.

**Comment by sh4rkman** [comment] 2024-06-30 23:49
should be fixed with f0538c4787287130403848a5d8cbcdb9c9509c04

**Closed by sh4rkman** 2024-06-30 23:49 UTC
Labels: bug, help wanted
